### ISSUE TITLE
Question about feature matching

### ISSUE THREAD

**Issue by amiltonwong** [vbalnt/pnnet#1]
Dear @vbalnt ,

I'm concerned about how to use PN-descriptor for doing feature matching within structure-from-motion pipeline. In conventional feature-based SfM, the first step is feature keypoints detection, and second step is feature extraction using feature descriptor (such as SIFT, SURF descriptor ).And then perform feature matching using comparison method. Could PN-descriptor be applied in conventional feature keypoints (like Harris, FAST, SIFT, SURF keypoints)?

Best~
Milton

**Comment by vbalnt** [comment]
Hi Milton,

you can indeed use the PN-descriptor with the conventional feature keypoints, you just have to extract keypoint-based rectified patches of size 32x32 around each keypoint. 

For examples on how to do that you can check code from Tomasz Trzcinski's [Binboost](http://infoscience.epfl.ch/record/186246/files/boostDesc_1.0.tar.gz) . E.g check the following function from `Utils.cpp`

```
void Utils::rectifyPatch(const Mat& image,
                     const KeyPoint& kp,
                     const int& patchSize,
                     Mat& patch)
```

You can also get lots of info in Sergey Szagoruyko's [deepcompare](https://github.com/szagoruyko/cvpr15deepcompare/tree/master/opencv) project on how to connect torch networks with openCV keypoints. The function [extractPatches](https://github.com/szagoruyko/cvpr15deepcompare/blob/master/opencv/example.cpp#L32-L49) also shows how to get normalized patches for use with deep networks from classical openCV keypoints.

**Comment by amiltonwong** [comment]
THX :) @vbalnt

**Comment by amiltonwong** [comment]
Hi, @vbalnt ,
One question:
Why do we need a rectified patch and not just a conventional patch?

**Comment by vbalnt** [comment]
These are needed for scale and rotation invariance. 

Each keypoint is associated with a specific scale (circle radius) and a specific angle. Without these you could not match images with extreme differences in scale and large rotations.

**Comment by vbalnt** [comment]
To add to this, you can take a look at @nenadmarkus work on how to use convolutional descriptors in a retrieval framework (it includes extracting patches around FAST and DoG keypoints). 

https://github.com/nenadmarkus/wlrn
