### ISSUE TITLE
DistanceRatioCriterion 

### ISSUE THREAD

**Issue by jade2014** [vbalnt/pnnet#12]
hello : 
      I have some question about the loss function in "run.lua" , line 154: "local f = crit:forward(outputs, 1)" .
![image](https://cloud.githubusercontent.com/assets/8266482/22199300/3e1ef2f6-e195-11e6-9a7c-1ac15b446732.png)
 In the loss function ,  the first part is compared with zero, the second part is compared with one. But in the forward , you all compare with one ? maybe my understanding is wrong . Can you tell me the reason. 
Thank you very much !

**Comment by mkaraki48** [comment]
@jade2014 Since this is a custom made criterion, the labels {0, 1} are generated here [https://github.com/vbalnt/pnnet/blob/master/train/DistanceRatioCriterion.lua#L14-L19](url).

**Comment by moustaphakaraki** [comment]
@jade2014 Since this is a custom made criterion, the labels {0, 1} are generated on the fly [here](https://github.com/vbalnt/pnnet/blob/master/train/DistanceRatioCriterion.lua#L14-L19).

**Comment by jade2014** [comment]
@mkaraki48 get it . Thank you very much.
