### ISSUE TITLE
How to train PN-NET

### ISSUE THREAD

**Issue by pribadihcr** [vbalnt/pnnet#2]
Hi,

How to train/fine-tuning the PN-NET?

many thanks for help!

**Comment by vbalnt** [comment]
Hi, 

The training code will be available soon. I will update this issue when it is. 

Vassilis

**Comment by valentinp** [comment]
Hi Vassilis,

Just a quick follow up to this question: do you have a timeline for when the training code will be available? Just read through your paper and I'm super interested in using PN-Net for a graduate course project.

Thanks!
Valentin

**Comment by vbalnt** [comment]
Hi Valentin, 

I will try to upload the training files by tomorrow. 

Vassilis

**Comment by vbalnt** [comment]
@pribadihcr  @valentinp 

Training code is now available. Let me know if there are any issues because its a bit messy.
