### ISSUE TITLE
A pre-trained model for CPU

### ISSUE THREAD

**Issue by pppoe** [vbalnt/pnnet#3]
Thanks for this nice work. Would it be possible for you to provide a pre-trained model for CPU-only machine? Ref: https://groups.google.com/forum/#!topic/torch7/ugBCwaoXw_s

Currently, with a torch compiled on a CPU-only machine, which has no 'cunn' package, the model is not readable and it throws out error message like "unknown Torch class <torch.CudaTensor>". 

It would be quite helpful for many users without GPU. Thanks!

**Comment by vbalnt** [comment]
Hi, 

can you try the methods described below? 

https://github.com/soumith/cudnn.torch/pull/76

**Comment by pppoe** [comment]
Thanks. But on a machine without CUDA, the cudnn module is not compiled. After installing torch, there is actually no cudnn module.

**Comment by shamangary** [comment]
I have to ask the same question here. It seems that the conversion can only be done when you are converting "nn to cudnn". According to the README.md from cudnn.torch, there is no "cudnn to nn conversion".

I post part of the README.md from https://github.com/soumith/cudnn.torch/blob/R4/README.md

---

Conversion between cudnn and nn

Conversion is done by cudnn.convert function which takes a network and backend arguments and goes over network modules recursively substituting equivalents. No memory copy is done, just metatables are swapped.

net = nn.Sequential()
net:add(nn.SpatialConvolution(3,96,11,11,3,3))
net:add(nn.ReLU())
cudnn.convert(net, cudnn)
print(net)
will result in:

nn.Sequential {
  [input -> (1) -> (2) -> output]
  (1): cudnn.SpatialConvolution(3 -> 96, 11x11, 3,3)
  (2): cudnn.ReLU
}

**Comment by vbalnt** [comment]
I will take a look at it and try to produce a nn only version soon.

**Comment by ngunsu** [comment]
Probably a bit too late... 

Anyway @shamangary  you can do both.
cudnn.convert(net, cudnn)    nn ->cudnn
cudnn.convert(net, nn)          cudnn-> nn

Cheers

**Comment by shamangary** [comment]
Thank you @ngunsu I will try it. However, since the computer without GPU will not have cudnn function, I guess I can use other computer to convert the file and then use the CPU only version. Thank you again.

**Comment by vbalnt** [comment]
@shamangary & @pppoe just commited an nn only version 

I didn’t know that its as easy as @ngunsu pointed out :).  Updated the repo with a nn only version. 
I haven't tested though, I hope it works fine. 

check commit: https://github.com/vbalnt/pnnet/commit/b124456ff8447d224f7310c51dae352c452eedb3

**Comment by mc-ddd** [comment]
It seems that the uploaded pnnet-liberty-nn.t7 still will not load without Cuda support.

This error is returned :
lua/5.1/torch/File.lua:334: unknown Torch class <torch.CudaTensor>

From the line :
local netC = torch.load('pnnet-liberty-nn.t7')

**Comment by shamangary** [comment]
BTW, it seems that cudatensor is used in the training process, so the cudnn->nn conversion might not be enough~

**Comment by ngunsu** [comment]
@shamangary  cudnn->nn just changes cudnn operations to nn. Then you have to cast to float.

> net = torch.load('pnnet.net')
> cudnn.convert(net, nn)
> net:float()

**Comment by shamangary** [comment]
@ngunsu THX
It seems that both "cudnn.convert" and "net:float()" cannot be done when your computer only have CPU instead of GPU. More accurately, it reports error when I use torch.load. Therefore, I cannot use pnnet-liberty-nn.t7 directly in my computer. QAQ

**Comment by vbalnt** [comment]
@ngunsu maybe I have to cast to float from my side with cuda so that people without cuda can use it?

**Comment by ngunsu** [comment]
@vbalnt Yes, you have to do the cast on your side.

**Comment by vbalnt** [comment]
@shamangary  can you try now? I did the casting to float. 
You should also probably check if the distance results have any meaning (run eval.lua and you should see negative pair distances being much larger than positive ones)

**Comment by shamangary** [comment]
@vbalnt OK. Let me try it now

**Comment by shamangary** [comment]
@vbalnt Sorry. Another error shows up.

/usr/local/bin/luajit: /usr/local/share/lua/5.1/torch/File.lua:301: Failed to load function from bytecode: (binary): cannot load incompatible bytecode
stack traceback:
    [C]: in function 'error'
    /usr/local/share/lua/5.1/torch/File.lua:301: in function 'readObject'
    /usr/local/share/lua/5.1/torch/File.lua:369: in function 'readObject'
    /usr/local/share/lua/5.1/nn/Module.lua:158: in function 'read'
    /usr/local/share/lua/5.1/torch/File.lua:351: in function 'readObject'
    /usr/local/share/lua/5.1/torch/File.lua:369: in function 'readObject'
    /usr/local/share/lua/5.1/torch/File.lua:369: in function 'readObject'
    /usr/local/share/lua/5.1/nn/Module.lua:158: in function 'read'
    /usr/local/share/lua/5.1/torch/File.lua:351: in function 'readObject'
    /usr/local/share/lua/5.1/torch/File.lua:409: in function 'load'
    extract.lua:10: in main chunk
    [C]: in function 'dofile'
    /usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x00406270

**Comment by vbalnt** [comment]
@shamangary  
Seems related to https://github.com/cmusatyalab/openface/issues/42 
I saved it in ascii format not binary. Can you try again?
Also what’s your architecture?

**Comment by shamangary** [comment]
I am not sure what do you mean by architecture, but I use Ubuntu 12.04.
Also, another error. QQ

/usr/local/bin/luajit: /usr/local/share/lua/5.1/torch/File.lua:375: unknown object
stack traceback:
    [C]: in function 'error'
    /usr/local/share/lua/5.1/torch/File.lua:375: in function 'readObject'
    /usr/local/share/lua/5.1/torch/File.lua:409: in function 'load'
    extract.lua:10: in main chunk
    [C]: in function 'dofile'
    /usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x00406270

**Comment by vbalnt** [comment]
@shamangary just to confirm did you use the torch.load 'ascii' when loading the file?
I suspect torch.load does some internal query to see the type but just in case.

**Comment by shamangary** [comment]
@vbalnt 
If I use

**net = torch.load('./pnnet-liberty-nn-ascii.t7','ascii')**

It reports

/usr/local/bin/luajit: /usr/local/share/lua/5.1/torch/File.lua:301: Failed to load function from bytecode: (binary): cannot load incompatible bytecode
stack traceback:
    [C]: in function 'error'
    /usr/local/share/lua/5.1/torch/File.lua:301: in function 'readObject'
    /usr/local/share/lua/5.1/torch/File.lua:369: in function 'readObject'
    /usr/local/share/lua/5.1/nn/Module.lua:158: in function 'read'
    /usr/local/share/lua/5.1/torch/File.lua:351: in function 'readObject'
    /usr/local/share/lua/5.1/torch/File.lua:369: in function 'readObject'
    /usr/local/share/lua/5.1/torch/File.lua:369: in function 'readObject'
    /usr/local/share/lua/5.1/nn/Module.lua:158: in function 'read'
    /usr/local/share/lua/5.1/torch/File.lua:351: in function 'readObject'
    /usr/local/share/lua/5.1/torch/File.lua:409: in function 'load'
    extract.lua:10: in main chunk
    [C]: in function 'dofile'
    /usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x00406270

---

If I use

**net = torch.load('./pnnet-liberty-nn-ascii.t7')**

it reports

/usr/local/bin/luajit: /usr/local/share/lua/5.1/torch/File.lua:375: unknown object
stack traceback:
    [C]: in function 'error'
    /usr/local/share/lua/5.1/torch/File.lua:375: in function 'readObject'
    /usr/local/share/lua/5.1/torch/File.lua:409: in function 'load'
    extract.lua:10: in main chunk
    [C]: in function 'dofile'
    /usr/local/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
    [C]: at 0x00406270

**Comment by ngunsu** [comment]
The ascii network works fine on my computer without cuda (macbook pro OSX). I think the problem is not related with the network itself now.  Maybe architecture, torch version...

**Comment by vbalnt** [comment]
Can confirm I tried on two different machines and the ascii version works fine. 
@shamangary try upgrading torch and all related libs?

@ngunsu  in theory ascii is just raw numbers shouldn't it be architecture independent?

**Comment by shamangary** [comment]
@vbalnt @ngunsu 
Thank you very much. After I update the luajit, I can read both "pnnet-liberty-nn.t7" and "pnnet-liberty-nn-ascii.t7" now.

**net = torch.load('./pnnet-liberty-nn.t7')**

or

**net = torch.load('./pnnet-liberty-nn-ascii.t7', 'ascii')**

---

I follow the steps of https://github.com/torch/luajit-rocks

**git clone https://github.com/torch/luajit-rocks.git
cd luajit-rocks
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=/your/prefix
sudo make install**

---

BTW. Can I ask @vbalnt to keep both "pnnet-liberty-nn.t7" and "pnnet-liberty-nn-ascii.t7". It would be more flexible to have both options. Thank you again.
