### ISSUE TITLE
New Oxford dataset

### ISSUE THREAD

**Issue by edgarriba** [vbalnt/pnnet#5]
Hi! First of all, congrats for this successful work. In the end of the paper you mention that you added new sequences to the Oxford dataset with associated text files, where can I download it? Thanks in advance!

**Comment by vbalnt** [comment]
The new dataset will be available soon. I will update this issue when it is with more details.

**Comment by vbalnt** [comment]
New dataset is now available at 

https://github.com/featw/hpatches

This dataset is part of the challenge for the ECCV-2016 workshop on local features

http://www.iis.ee.ic.ac.uk/ComputerVision/DescrWorkshop/
