### ISSUE TITLE
Line 253 and 795 of the ASCII formatted nn network performs strange binary-encoded file accesses to the Torch install

### ISSUE THREAD

**Issue by mdaiter** [vbalnt/pnnet#6]
Hey all,
When looking at the pnnet ASCII-formatted t7 file, I stumbled upon a pretty strange line on 253 and 795 that attempts to access the Module.lua directory in a specific install version of Torch 5.1. Not only can I see the general overview of the author's home formatting (privacy issue in and of itself) but also this messes up loading from other frameworks; in specific, thnets. I was wondering if I could remove this line. Will the net still operate in the same way?

**Comment by vbalnt** [comment]
Hi, this probably is a problem with the way the ASCII formatted net is saved, so it has to do with the torch lib itself. 

Can you try to load the binary file instead? Is this supported by thnets?
If the bin file works then I can remove the ASCII version, which I don't think is needed. 

Thanks

**Comment by mdaiter** [comment]
@vbalnt Just tried loading the binary format It also gives errors.
I think the core difference is when using LUAJIT 2.1 vs LUA 5.1 or LUA 5.2. When using Lua 5.1 or 5.2, the entire library breaks. When LUAJIT 2.1 is used, everything works as expected.

This is due to a versioning and serialising error, as @soumith details here: https://github.com/torch/torch7/issues/641 . It appears as though you have serialised a function directly into your net, which LUAJIT skips over but LUA 5.1 and 5.2 hiccup on.

**Comment by mdaiter** [comment]
@vbalnt here's the stack trace when attempting a load with LUA 5.1:
`...me/nomoko/torch/install/share/lua/5.1/torch/File.lua:301: Failed to load function from bytecode: binary string: bad header in precompiled chunk
stack traceback:
    ...me/nomoko/torch/install/share/lua/5.1/trepl/init.lua:501: in function <...me/nomoko/torch/install/share/lua/5.1/trepl/init.lua:494>
    [C]: in function 'error'
    ...me/nomoko/torch/install/share/lua/5.1/torch/File.lua:301: in function 'readObject'
    ...me/nomoko/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
    ...ome/nomoko/torch/install/share/lua/5.1/nn/Module.lua:158: in function 'read'
    ...me/nomoko/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
    ...me/nomoko/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
    ...me/nomoko/torch/install/share/lua/5.1/torch/File.lua:369: in function 'readObject'
    ...ome/nomoko/torch/install/share/lua/5.1/nn/Module.lua:158: in function 'read'
    ...me/nomoko/torch/install/share/lua/5.1/torch/File.lua:351: in function 'readObject'
    ...me/nomoko/torch/install/share/lua/5.1/torch/File.lua:409: in function 'load'
    [string "obj = torch.load('./pnnet-liberty.t7')"]:1: in main chunk
    [C]: in function 'xpcall'
    ...me/nomoko/torch/install/share/lua/5.1/trepl/init.lua:669: in function 'repl'
    .../torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
    [C]: ?  
`

**Comment by mdaiter** [comment]
@vbalnt here's another example: https://github.com/torch/torch7/issues/601

@szagoruyko, in this, says "there is a function saved with luajit2.1 that's incompatible with your lua for some reason. I will repack it without the function". Could you please repack your neural net without the function? For the custom loader I'm working on, I'm trying to load in your net in C++ and the recursive function lookup that the 8 symbolises before the
56
270
(random characters) /home/vassilis/(random characters)
is really messing up the loading mechanism.

**Comment by vbalnt** [comment]
> > I will repack it without the function

Which part of the network is causing the problem? I will remove it if its possible.

**Comment by mdaiter** [comment]
@vbalnt it's within accUpdateGradParameters, which is marked in the ASCII as a recursive function (Line 250 = 8). It appears to happen right before the Tanh step on both occurrences.

**Comment by mdaiter** [comment]
@vbalnt what you might want to do for maximum flexibility is create two versions of the net: one binary/ASCII version (whichever you prefer, it's easily convertible within the th REPL) without the accUpdateGradParameters that can be used for a "release version" without the ability to train it, and one with the accUpdateGradParameters that allows for a "development version". That way, people can choose which version is appropriate.

If you'd like help, I'd love to help!

**Comment by vbalnt** [comment]
@mdaiter  thanks, time is pretty limited now, so I can either try it next week, or If you would like to help that would be great, just send a request and I will add it to the repo. 

Thanks

**Comment by mdaiter** [comment]
@vbalnt I'll see what I can do

**Comment by mdaiter** [comment]
@vbalnt think I made some headway; however, I seem to be getting different descriptor outputs between description pass-throughs. Is it alright if I removed the accUpdateGradParameters? That's the only function I need to remove. Once that's gone, the rest of your library is compatible with Lua 5.1 and 5.2

**Comment by vbalnt** [comment]
Hi, this seems fine if you want you can send a request.

Do you have a script to do that? 
It would be also useful for the newer versions of the networks coming up.

**Comment by mdaiter** [comment]
@vbalnt don't have a script for that
I can send a request shortly.
