### ISSUE TITLE
Neg and Pos

### ISSUE THREAD

**Issue by shamangary** [vbalnt/pnnet#7]
Hello. I was digging the code, and I found a typo (maybe).

In "run.lua", there should be two negative distance for the latter mining.
(line: 55~87)
However, the notations are two positive distance for the cnn_left and cnn_left2, and one negative for cnn_right.

This will not affect the results but I think these names should be corrected?

Thank you for your time.

**Comment by vbalnt** [comment]
Hi, you are right, this seems like a variable naming issue. 

However, the wrongly-named module is placed in the correct place in the network. 

If you have a fix you can send a request, otherwise I will fix it 

Thanks
