### ISSUE TITLE
Notredame and Yosemite networks

### ISSUE THREAD

**Issue by ngunsu** [vbalnt/pnnet#8]
Hi,

Could you provide Notre-Dame and Yosemite trained networks?.

**Comment by vbalnt** [comment]
Hi, sorry for the late reply I was on holidays. 

Here are newer versions of the networks trained for a BMVC paper. These networks should perform much better than the ones in this repo.

http://www.iis.ee.ic.ac.uk/~vbalnt/tfeat/

I will also update the repo soon to include the details from a new BMVC paper.
